# Generated by Django 3.1 on 2020-10-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agr1', models.IntegerField()),
                ('Agr10', models.IntegerField()),
                ('Agr2', models.IntegerField()),
                ('Agr3', models.IntegerField()),
                ('Agr4', models.IntegerField()),
                ('Agr5', models.IntegerField()),
                ('Agr6', models.IntegerField()),
                ('Agr7', models.IntegerField()),
                ('Agr8', models.IntegerField()),
                ('Agr9', models.IntegerField()),
                ('Csn1', models.IntegerField()),
                ('Csn10', models.IntegerField()),
                ('Csn2', models.IntegerField()),
                ('Csn3', models.IntegerField()),
                ('Csn4', models.IntegerField()),
                ('Csn5', models.IntegerField()),
                ('Csn6', models.IntegerField()),
                ('Csn7', models.IntegerField()),
                ('Csn8', models.IntegerField()),
                ('Csn9', models.IntegerField()),
                ('Est1', models.IntegerField()),
                ('Est10', models.IntegerField()),
                ('Est2', models.IntegerField()),
                ('Est3', models.IntegerField()),
                ('Est4', models.IntegerField()),
                ('Est5', models.IntegerField()),
                ('Est6', models.IntegerField()),
                ('Est7', models.IntegerField()),
                ('Est8', models.IntegerField()),
                ('Est9', models.IntegerField()),
                ('Ext1', models.IntegerField()),
                ('Ext10', models.IntegerField()),
                ('Ext2', models.IntegerField()),
                ('Ext3', models.IntegerField()),
                ('Ext4', models.IntegerField()),
                ('Ext5', models.IntegerField()),
                ('Ext6', models.IntegerField()),
                ('Ext7', models.IntegerField()),
                ('Ext8', models.IntegerField()),
                ('Ext9', models.IntegerField()),
                ('Opn1', models.IntegerField()),
                ('Opn10', models.IntegerField()),
                ('Opn2', models.IntegerField()),
                ('Opn3', models.IntegerField()),
                ('Opn4', models.IntegerField()),
                ('Opn5', models.IntegerField()),
                ('Opn6', models.IntegerField()),
                ('Opn7', models.IntegerField()),
                ('Opn8', models.IntegerField()),
                ('Opn9', models.IntegerField()),
            ],
        ),
    ]
